# Setup
title:               BD
tagline:             'Tunnels, Geotechnics and Codes'
description:         'A personal website to share notes on tunnels, geotechnical engineering and codes. <br>- Berk Demir'
url:                 https://berkdemir.github.io
baseurl:             ''
paginate:            30
permalink:           pretty


# About/contact
author:
  name:              Berk Demir
  url:               www.linkedin.com/in/bdberkdemir
  email:             bdberkdemir@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-83ZFJ7ZVDV
